# Generated by Django 4.2.1 on 2023-06-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_remove_task_created_task_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
    ]
