# Generated by Django 4.2.1 on 2023-06-13 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_rename_title_task_task_remove_task_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
    ]
