# Generated by Django 4.2.1 on 2023-06-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0005_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
