# Generated by Django 4.2.2 on 2023-06-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0009_alter_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(default=None, max_length=150, null=True, upload_to='taskfiles/'),
        ),
    ]
